config/routes.rb
Rails.application.routes.draw do

  resources :sessions , only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'


  resources :users

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }

  def to_s
    "#{username}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
    else
      render :new
    end
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :name, :gender, :about_me, :cooking_expertise, :location)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flourlicious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- navbar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
      <!-- navbar brand -->
        <div class="navbar-header">
           <ul class="nav navbar-nav">
             <li><a href="/" class="navbar-brand" id="brand">Flourlicious</a></li>
           </ul>
         </div>
         <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><a href="/users/<%=current_user.id%>"><span class="glyphicon glyphicon-user"></span> <%= current_user.username %></a></li>
              <li><%= link_to logout_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span>  Logout
              <% end %></li>
            <% else %>
              <li><a data-toggle="modal" data-target="#mySignup">Sign Up</a></li>
              <li><a data-toggle="modal" data-target="#myLogin">Log In</a></li>
            <% end %>
          </ul>
      </div>
    </nav>

    <!-- Sign-up modal -->
    <div class="modal" id="mySignup">
      <div class="modal-dialog modal-sm">
        <div class="modal-signup-content">
          <!-- header -->
          <div class="modal-signup-header" id="signup-header-modal">
            <button type="button" class="close" data-dismiss='modal'>&times;</button>
            <h1 class="modal-signup-title" id="modal-signup">Sign Up </h1>
          </div>
          <!-- signup form -->
          <div class="modal-signup-body">
            <%= form_for User.new do |form| %>
            <div class="form-group">
              <%= form.label :username, class:"sr-only" %>
              <%= form.text_field :username, placeholder:"Username", class:"form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :email, class:"sr-only" %>
              <%= form.email_field :email, placeholder:"Email", class:"form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :password, class:"sr-only" %>
              <%= form.password_field :password, placeholder:"Password", class:"form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :password_confirmation, class:"sr-only" %>
              <%= form.password_field :password_confirmation, placeholder:"Re-confirm password", class:"form-control" %>
            </div>

            <!-- submit button -->
            <div class="submit-field">
              <%= button_tag "Sign up", type: "submit", class: "btn btn-basic btn-block" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<!-- Login Modal -->
    <div class="modal fade" id="myLogin">
      <div class="modal-dialog modal-sm">
        <div class="modal-login-content">
          <!-- header -->
          <div class="modal-login-header">
            <button type="button" class="close" data-dismiss='modal'>&times;</button>
            <h1 class="modal-login-title" id="modal-login">Log In </h1>
          </div>
          <!-- signup form -->
          <div class="modal-login-body">
            <%= form_for :sessions, url: sessions_path do |form| %>
            <div class="form-group">
              <%= form.label :email, class:"sr-only" %>
              <%= form.email_field :email, placeholder:"Email", class:"form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :password, class:"sr-only" %>
              <%= form.password_field :password, placeholder:"Password", class:"form-control" %>
            </div>
            <!-- submit button -->
            <div class="submit-field">
              <%= button_tag "Log In", type: "submit", class: "btn btn-basic btn-block" %>
              <% end %>
            </div><br>
            <!-- link to signup form -->
            <p id="not-register-yet">Not a member?<a data-toggle="modal" data-target="#mySignup" data-dismiss='myLogin' id="signup-here"> Sign Up Here</a></p>
          </div>
        </div>
      </div>
    </div>
    <!-- javascript for hide login modal -->
    <script type="text/javascript">
    $('#signup-here').click(function() {
        $('#myLogin').modal('hide');
      });
    </script>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= f.label :username %>
        <%= f.text_field :username, type: 'username', class: "form-control" %>
        <br>
        <%= f.label :email %>
        <%= f.text_field :email, type: 'email', class: "form-control"%>
        <br>
        <%= f.label :name %>
        <%= f.text_field :name, type: 'name', class: "form-control" %>
        <br>
        <%= f.label :cooking_expertise %>
        <%= f.text_field :cooking_expertise, type: 'cooking_expertise', class: "form-control" %>
        <br>
        <%= f.label :gender %>
        <%= f.text_field :gender, type: 'gender', class: "form-control" %>
        <br>
        <%= f.label :location %>
        <%= f.text_field :location, type: 'location', class: "form-control" %>
        <br>
        <%= f.label :about_me %>
        <%= f.text_field :about_me, type: 'about_me', class: "form-control" %>
        <br>
        <%= f.label :password %>
        <%= f.password_field :password, type: 'password', class: "form-control" %>
        <br>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, type: 'password_confirmation', class: "form-control" %>
        <br>
        <%= button_tag "Edit Profile", type: "submit", class: "btn btn-basic btn-block"%>
        <% end %>
        <br>
        <div style="text-align:center;"><%= link_to 'Back', user_path %></div>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<h1 style="text-align:center;">Edit Profile</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container-fluid" id="profile-page">
  <div class="jumbotron" id="profile-jumbo">
      <h1 id="user-name">
      <%= @user.name %>
      </h1>
  </div>
</div>

<div class="container-fluid" id="about-me-container">

  <h2 id="about-me">About Me</h2>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Cooking Expertise:</strong>
  <%= @user.cooking_expertise %>
</p>

<p>
  <strong>More about me:</strong>
  <%= @user.about_me %>
</p>

<%= link_to 'Edit Profile', edit_user_path(@user) %>

</div>

<div class="container-fluid" id="profile-recipes-container">
  <h3 id="profile-recipes"> My Recipes </h3>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="jumbotron" id="homepage-jumbo">
  <h1 id="main-heading">Flourlicious</h1><br>
  <p id="web-description">The best baking recipes for everyone.</p>
</div>
</div>

<div class="container-fluid" id="latest-recipes">
  <h2 id="latest-recipes"> Latest Recipes </h2>
</div>